#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""
Generate heads/chimneys.yml from the raw head-database CSV.

Chimneys live in generators/heads-db.csv (category `decoration`) but were never part of HeadSmith's
curated head set. This emits a head definition for every chimney texture variant, tagged
`properties: [chimney]` so the converter gives them the candle-like "chimney" behavior (light-less,
rising campfire smoke). Give-only (no recipes). Output is committed like the other authored heads.

Run:  uv run headsmith/tools/gen_chimneys.py
"""
from __future__ import annotations

import base64
import json
import re
from collections import Counter
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CSV = HERE / "source" / "generators" / "heads-db.csv"
OUT = HERE / "source" / "heads" / "chimneys.yml"


def texture_b64(hash_: str) -> str:
    doc = {"textures": {"SKIN": {"url": f"http://textures.minecraft.net/texture/{hash_}"}}}
    return base64.b64encode(json.dumps(doc).encode()).decode()


def slug(material: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", material.lower()).strip("_")
    return s


def main() -> int:
    heads: dict[str, dict] = {}
    seen_hash: set[str] = set()
    id_counts: Counter[str] = Counter()

    for line in CSV.read_text().splitlines():
        # cols: name, category, hash, tags  (name has no comma; tags may)
        parts = line.split(",", 3)
        if len(parts) < 3:
            continue
        name, _category, hash_ = parts[0].strip(), parts[1].strip(), parts[2].strip()
        if not name.lower().startswith("chimney"):
            continue
        if hash_ in seen_hash:
            continue  # identical texture — skip duplicate variant
        seen_hash.add(hash_)

        m = re.search(r"\(([^)]+)\)", name)
        material = m.group(1) if m else ""
        base_id = "chimney" if not material else f"chimney_{slug(material)}"
        id_counts[base_id] += 1
        head_id = base_id if id_counts[base_id] == 1 else f"{base_id}_{id_counts[base_id]}"

        # Display name: "Chimney" or "Chimney (Cobblestone)"
        disp = "Chimney" if not material else f"Chimney ({material.title()})"

        heads[head_id] = {
            "texture": texture_b64(hash_),
            "name": f"&7{disp}",
            "properties": ["chimney"],
        }

    doc = {"heads": heads}
    with OUT.open("w") as fh:
        fh.write("# GENERATED by headsmith/tools/gen_chimneys.py from the head-database CSV.\n")
        fh.write("# Chimneys: candle-like interactive heads (no light, campfire smoke when lit).\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=100000, default_flow_style=False)

    print(f"Wrote {len(heads)} chimney heads -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
