#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""
Generate heads/chimneys.yml from the raw head-database CSV.

Chimneys live in generators/heads-db.csv (category `decoration`) but were never part of HeadSmith's
curated head set. This emits a head definition for every chimney texture variant, tagged
`properties: [chimney]` so the converter gives them the candle-like "chimney" behavior (light-less,
rising campfire smoke). Give-only (no recipes). Output is committed like the other authored heads.

Run:  uv run headsmith/tools/gen_chimneys.py
"""
from __future__ import annotations

import base64
import json
import re
from collections import Counter
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CSV = HERE / "source" / "generators" / "heads-db.csv"
OUT = HERE / "source" / "heads" / "chimneys.yml"

# Chimney base-material name (from the CSV "(…)" suffix, lowercased; "" = plain "Chimney")
# -> the Bukkit block you feed into a stonecutter to cut the chimney. Plain and "metal"
# have no obvious block, so they map to bricks / iron block respectively.
MATERIAL_BLOCK: dict[str, str] = {
    "": "BRICKS",
    "metal": "IRON_BLOCK",
    "iron": "IRON_BLOCK",
    "andesite": "ANDESITE",
    "polished andesite": "POLISHED_ANDESITE",
    "blackstone": "BLACKSTONE",
    "polished blackstone": "POLISHED_BLACKSTONE",
    "bricks": "BRICKS",
    "cobblestone": "COBBLESTONE",
    "mossy cobblestone": "MOSSY_COBBLESTONE",
    "stone": "STONE",
    "stone bricks": "STONE_BRICKS",
    "cracked stone bricks": "CRACKED_STONE_BRICKS",
    "mossy stone bricks": "MOSSY_STONE_BRICKS",
    "diorite": "DIORITE",
    "polished diorite": "POLISHED_DIORITE",
    "granite": "GRANITE",
    "polished granite": "POLISHED_GRANITE",
    "deepslate tile": "DEEPSLATE_TILES",
    "end stone": "END_STONE",
    "nether bricks": "NETHER_BRICKS",
    "red nether bricks": "RED_NETHER_BRICKS",
    "prismarine": "PRISMARINE",
    "prismarine brick": "PRISMARINE_BRICKS",
    "dark prismarine": "DARK_PRISMARINE",
    "sandstone": "SANDSTONE",
    "red sandstone": "RED_SANDSTONE",
}


def texture_b64(hash_: str) -> str:
    doc = {"textures": {"SKIN": {"url": f"http://textures.minecraft.net/texture/{hash_}"}}}
    return base64.b64encode(json.dumps(doc).encode()).decode()


def slug(material: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", material.lower()).strip("_")
    return s


def main() -> int:
    heads: dict[str, dict] = {}
    seen_hash: set[str] = set()
    id_counts: Counter[str] = Counter()

    for line in CSV.read_text().splitlines():
        # cols: name, category, hash, tags  (name has no comma; tags may)
        parts = line.split(",", 3)
        if len(parts) < 3:
            continue
        name, _category, hash_ = parts[0].strip(), parts[1].strip(), parts[2].strip()
        if not name.lower().startswith("chimney"):
            continue
        if hash_ in seen_hash:
            continue  # identical texture — skip duplicate variant
        seen_hash.add(hash_)

        m = re.search(r"\(([^)]+)\)", name)
        material = m.group(1) if m else ""
        base_id = "chimney" if not material else f"chimney_{slug(material)}"
        id_counts[base_id] += 1
        head_id = base_id if id_counts[base_id] == 1 else f"{base_id}_{id_counts[base_id]}"

        # Display name: "Chimney" or "Chimney (Cobblestone)"
        disp = "Chimney" if not material else f"Chimney ({material.title()})"

        head: dict = {
            "texture": texture_b64(hash_),
            "name": f"&7{disp}",
            "properties": ["chimney"],
        }
        # Craft in a stonecutter from the matching base block (all variants of a material share it).
        block = MATERIAL_BLOCK.get(material.lower())
        if block is None:
            print(f"  WARNING: no stonecutter block mapped for material {material!r} ({name}) — give-only")
        else:
            head["recipes"] = {"stonecutter": [{"id": head_id, "input": {"material": block}}]}
        heads[head_id] = head

    doc = {"heads": heads}
    with OUT.open("w") as fh:
        fh.write("# GENERATED by headsmith/tools/gen_chimneys.py from the head-database CSV.\n")
        fh.write("# Chimneys: candle-like interactive heads (no light, campfire smoke when lit).\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=100000, default_flow_style=False)

    print(f"Wrote {len(heads)} chimney heads -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
