name: DefCoreLib
main: anon.def9a2a4.corelib.CoreLibPlugin
version: ${version}
api-version: 1.21
author: def9a2a4
description: Shared core library for def plugins
commands:
  defcorelib:
    description: DefCoreLib admin commands
    usage: /defcorelib <give|give_demo|list|colliders|reloadbanners|cleanorphans> [args...]
    permission: corelib.admin
